#pragma once

// D-I-3: shared Host control IDs / custom messages / timers for multi-TU OcrDashboardWindow.

#define WM_DASHBOARD_OCR_COMPLETE (WM_USER + 101)
#define WM_DASHBOARD_RUN_OCR (WM_USER + 102)
#define WM_DASHBOARD_PDF_RENDER_COMPLETE (WM_USER + 103)
#define WM_DASHBOARD_PDF_COVER_COMPLETE (WM_USER + 104)
#define WM_DASHBOARD_THUMBNAIL_READY (WM_USER + 105)
#define WM_DASHBOARD_CLOUD_NATIVE_PDF_COMPLETE (WM_USER + 106)

#define TIMER_STATUS_CLEAR 1
#define TIMER_ZOOM_HUD 2
#define TIMER_IMAGE_HINT 3
#define TIMER_SOURCE_THUMBNAIL_WARMUP 4
#define TIMER_ACTIVE_WORK 5
#define TIMER_SEARCH_DEBOUNCE 6 // P1.3: search input debounce

#define ID_DASH_COPY 1001
#define ID_DASH_CLEAR 1002
#define ID_DASH_CLOSE 1003
#define ID_DASH_SEARCH 1004
#define ID_DASH_PREVIEW 1005
#define ID_DASH_SOURCE 1006
#define ID_DASH_PREV_RECORD 1007
#define ID_DASH_NEXT_RECORD 1008
#define ID_DASH_SOURCE_LIST 1009
#define ID_DASH_IMPORT 1010
#define ID_DASH_TEXT 1011
#define ID_DASH_JSON 1012
#define ID_DASH_OPEN_OUTPUT 1013
#define ID_DASH_RETRY_FAILED 1014
#define ID_DASH_PAUSE_BATCH 1017
#define ID_DASH_OCR_MODE 1019
#define ID_DASH_OUTPUT_FOLDER 1020
#define ID_DASH_LANG_TOGGLE 1023 // P1.5: runtime language toggle
#define ID_DASH_SOURCE_PANEL_TOGGLE 1024
#define ID_DASH_RESULT_PANEL_TOGGLE 1025
#define ID_DASH_SOURCE_SORT 1026
#define ID_DASH_TRANSLATE 1027
#define ID_DASH_TRANSLATE_AGAIN 1028
#define ID_DASH_MINIMIZE 1029
#define ID_DASH_MAXIMIZE 1030

#define ID_SOURCE_CTX_COPY 1301
#define ID_SOURCE_CTX_OPEN_OUTPUT 1302
#define ID_SOURCE_CTX_RETRY_FAILED 1303
#define ID_SOURCE_CTX_DELETE 1304
#define ID_SOURCE_CTX_REVEAL 1305
#define ID_SOURCE_CTX_PAUSE_ITEM 1306
#define ID_SOURCE_CTX_RERUN_ITEM 1307
#define ID_SOURCE_SORT_NEWEST 1311
#define ID_SOURCE_SORT_OLDEST 1312
